title: AI & Public Feedback
description: Research, practice, & beyond
baseurl: ""
url: "https://publicfeedback.ai"

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  quiet_deps: true
  silence_deprecations: [import, global-builtin, color-functions]

# Header links
header_pages:
  # - about.md
  # - resources.md
